### ISSUE TITLE
"invalid memory address or nil pointer dereference" panic on malformed AppRole login

### ISSUE THREAD

**Issue by mossblaser** [openbao/openbao#509]
I have stumbled upon a way to trigger a panic using the /auth/approle/login API endpoint of OpenBao using a simple malformed request.

**Describe the bug**

In a request to `/auth/approle/login`, setting either the `role_id` or `secret_id` parameters to an object (i.e. `{}`) rather than a string triggers the issue. This results in the connection being closed to the client without a response being sent. On the server side, a log message beginning with the following (followed by a stack trace) is seen:

     [INFO]  http: panic serving 127.0.0.1:54504: runtime error: invalid memory address or nil pointer dereference
    <...stack trace...>

<details>
<summary>Full output with stack trace (click to expand)</summary>

```
2024-09-05T08:12:48.249+0100 [INFO]  http: panic serving 127.0.0.1:54504: runtime error: invalid memory address or nil pointer dereference
goroutine 945 [running]:
net/http.(*conn).serve.func1()
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:1903 +0xbe
panic({0x3428060?, 0x649f2d0?})
        /opt/hostedtoolcache/go/1.22.6/x64/src/runtime/panic.go:770 +0x132
github.com/openbao/openbao/vault.(*Core).aliasNameFromLoginRequest(0xc000806e08, {0x45622f8, 0xc000d6f530}, 0xc00080c1a0)
        /home/runner/work/openbao/openbao/vault/core.go:3692 +0x37a
github.com/openbao/openbao/vault.(*Core).getLoginUserInfoKey(0xc001104540?, {0x45622f8?, 0xc000d6f530?}, 0xc00059b180, 0xc001104540?)
        /home/runner/work/openbao/openbao/vault/request_handling.go:1710 +0x29
github.com/openbao/openbao/vault.(*Core).isUserLocked(0xc000806e08, {0x45622f8, 0xc000d6f530}, 0xc00059b180, 0xc000b265d0?)
        /home/runner/work/openbao/openbao/vault/request_handling.go:1763 +0x3f
github.com/openbao/openbao/vault.(*Core).handleLoginRequest(0xc000806e08, {0x45622f8, 0xc000d6f530}, 0xc00080c1a0)
        /home/runner/work/openbao/openbao/vault/request_handling.go:1290 +0xae6
github.com/openbao/openbao/vault.(*Core).handleCancelableRequest(0xc000806e08, {0x45622f8, 0xc000d6f530}, 0xc00080c1a0)
        /home/runner/work/openbao/openbao/vault/request_handling.go:695 +0x11d8
github.com/openbao/openbao/vault.(*Core).switchedLockHandleRequest(0xc000806e08, {0x45622f8, 0xc000d6f080}, 0xc00080c1a0, 0x1)
        /home/runner/work/openbao/openbao/vault/request_handling.go:529 +0x605
github.com/openbao/openbao/vault.(*Core).HandleRequest(...)
        /home/runner/work/openbao/openbao/vault/request_handling.go:482
github.com/openbao/openbao/http.request(0xc000806e08, {0x4552140, 0xc000d6efc0}, 0xc000d145a0, 0xc00080c1a0)
        /home/runner/work/openbao/openbao/http/handler.go:819 +0x7f
github.com/openbao/openbao/http.handler.handleLogical.handleLogicalInternal.func57({0x4552140, 0xc000d6efc0}, 0xc000d145a0)
        /home/runner/work/openbao/openbao/http/logical.go:356 +0xa6
net/http.HandlerFunc.ServeHTTP(0x725b871bd108?, {0x4552140?, 0xc000d6efc0?}, 0xc000d6f380?)
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:2171 +0x29
github.com/openbao/openbao/http.handler.handleRequestForwarding.func35({0x4552140, 0xc000d6efc0}, 0xc000d145a0)
        /home/runner/work/openbao/openbao/http/handler.go:744 +0xbc
net/http.HandlerFunc.ServeHTTP(0xc001359450?, {0x4552140?, 0xc000d6efc0?}, 0x615aa8?)
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:2171 +0x29
net/http.(*ServeMux).ServeHTTP(0xc000a9ca80?, {0x4552140, 0xc000d6efc0}, 0xc000d145a0)
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:2688 +0x1ad
github.com/openbao/openbao/http.handler.wrapHelpHandler.func47({0x4552140, 0xc000d6efc0}, 0xc000d145a0)
        /home/runner/work/openbao/openbao/http/help.go:28 +0xfd
net/http.HandlerFunc.ServeHTTP(0x0?, {0x4552140?, 0xc000d6efc0?}, 0xc000a89428?)
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:2171 +0x29
github.com/openbao/openbao/http.handler.wrapCORSHandler.func48({0x4552140, 0xc000d6efc0}, 0xc000d145a0)
        /home/runner/work/openbao/openbao/http/cors.go:32 +0x389
net/http.HandlerFunc.ServeHTTP(0xc000806e08?, {0x4552140?, 0xc000d6efc0?}, 0xc001314ea0?)
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:2171 +0x29
github.com/openbao/openbao/http.handler.rateLimitQuotaWrapping.func49({0x4552140, 0xc000d6efc0}, 0xc000d145a0)
        /home/runner/work/openbao/openbao/http/util.go:156 +0x9bf
net/http.HandlerFunc.ServeHTTP(0xc000d6ef00?, {0x4552140?, 0xc000d6efc0?}, 0xc000a70070?)
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:2171 +0x29
github.com/openbao/openbao/http.wrapGenericHandler.func1({0x4551350, 0xc0002261c0}, 0xc000d14000)
        /home/runner/work/openbao/openbao/http/handler.go:421 +0xd35
net/http.HandlerFunc.ServeHTTP(0xc0012b6000?, {0x4551350?, 0xc0002261c0?}, 0xc000a9c180?)
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:2171 +0x29
github.com/openbao/openbao/http.handler.wrapMaxRequestSizeHandler.func50({0x4551350, 0xc0002261c0}, 0xc0012b6000)
        /home/runner/work/openbao/openbao/http/util.go:58 +0x122
net/http.HandlerFunc.ServeHTTP(0xc0006de005?, {0x4551350?, 0xc0002261c0?}, 0x0?)
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:2171 +0x29
github.com/openbao/openbao/http.handler.PrintablePathCheckHandler.func51({0x4551350, 0xc0002261c0}, 0xc0012b6000)
        /home/runner/go/pkg/mod/github.com/hashicorp/go-cleanhttp@v0.5.2/handlers.go:42 +0x8f
net/http.HandlerFunc.ServeHTTP(0x412045?, {0x4551350?, 0xc0002261c0?}, 0xc000226101?)
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:2171 +0x29
net/http.serverHandler.ServeHTTP({0x4546648?}, {0x4551350?, 0xc0002261c0?}, 0x6?)
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:3142 +0x8e
net/http.(*conn).serve(0xc000672240, {0x45622f8, 0xc0008221b0})
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:2044 +0x5e8
created by net/http.(*Server).Serve in goroutine 817
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:3290 +0x4b4
```

</details>

I have not observed any other side effects (e.g. the server remains up and responsive to further requests).

**To Reproduce**

Start up an OpenBao instance, e.g.:

    $ bao server -dev

Enable the AppRole auth method:

    $ BAO_ADDR="http://localhost:8200" BAO_TOKEN="..." bao auth enable approle
    Success! Enabled approle auth method at: approle/

Send a malformed request with either `role_id` or `secret_id` set to `{}`, for example:

    $ curl \
        --request POST \
        --header "Content-Type: application/json" \
        --data '{"role_id": {}, "secret_id": ""}' \
        http://localhost:8200/v1/auth/approle/login
    curl: (52) Empty reply from server

Observe connection closing before a response is received by the client. Also observe panic and stack trace (as shown above) in the OpenBao logs.

**Expected behavior**

I would expect some kind of 4xx error about a malformed request and no messages in the OpenBao logs.

**Environment:**
* OpenBao v2.0.1 (88383dece6b4ff1b3b242280a54aeabef8101495), built 2024-09-03T19:57:34Z
* Ubuntu 22.04.4 LTS, x86_64

**Additional context**
The same bug exists in Hashicorp Vault (and I have also [reported the issue there](https://github.com/hashicorp/vault/issues/28282)).

**Comment by cipherboy** [comment]
@mossblaser My read is the guard on 3689 is incorrect:

https://github.com/openbao/openbao/blob/21bd39e4352352335f1b53a5a7118ef62a96267f/vault/core.go#L3689

And should probably guard against `resp` and `resp.Alias` being `nil`. Are you interested in opening a PR? Otherwise I'm happy to handle it.

**Comment by mossblaser** [comment]
> Are you interested in opening a PR? Otherwise I'm happy to handle it.

I'm afraid I'm still new enough to Go and short enough on time that I'm probably not, sorry!

Thanks very much!

**Comment by cipherboy** [comment]
Ahh, tricky :-)

```
--- FAIL: TestAppRole_NilRoleId (0.00s)
    path_login_test.go:399: err:<nil> resp:&logical.Response{Secret:<nil>, Auth:<nil>, Data:map[string]interface {}{"error":"Field validation failed: error converting input map[] for field \"role_id\": '' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[]'"}, Redirect:"", Warnings:[]string(nil), WrapInfo:(*wrapping.ResponseWrapInfo)(nil), Headers:map[string][]string(nil)}
```

So this is a logical response with `resp.Data["error"]` set to a value, which means `resp.Auth` is nil:
