### ISSUE TITLE
Bug - Rabbitmq secret engine crashes vault on role read

### ISSUE THREAD

**Issue by cipherboy** [openbao/openbao#97]
As reported by @mr-miles on https://github.com/hashicorp/vault/issues/25112:

> **Describe the bug** Reading the details of a rabbitmq role from vault appears to crash the process
> 
> I am able to add a new role successfully, but reading the details of the role after creation causes strange errors and appears to make the vault container crash and restart.
> 
> I found the problem because it was crashing our terraform deployments, however I am able to reproduce it through the http api and the web ui command line.
> 
> Comparing the rabbitmq secret backend and the database one, the only difference I can see is e.g.
> 
> https://github.com/hashicorp/vault/blob/2acac70160962a61b21f2e1355fa052e464f7f75/builtin/logical/rabbitmq/path_roles.go#L110
> - the database plugin constructs a map[string]interface{} rather than
> structs.New(role).Map(). (this may be my amateur reading of the go code though).
> 
> Failing that, my other hunch is that the the interaction between the plugin and the storage is not quite right, so the role creation is storing something that blows up when read back out
> 
> Are there any pointers about how the plugins work so I could contribute some useful debugging information?
> 
> I can also see that path_roles.go lacks its test file so I will try to poke around there too
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. vault secrets enable rabbitmq
> 
>     2. vault write rabbitmq/config/connection connection_uri=xxx username=xxx password=xxx
> 
>     3. vault write rabbitmq/roles/newrole vhosts='{"/":{"write": ".*", "read": ".*"}}'
> 
>     4. vault read rabbitmq/roles/newrole
> 
> 
> In the web ui, a redirect is returned causing the command to not return. From the logs it appears the redirect is masking a restart of the container.
> 
> **Expected behavior**
> 
> The role details as defined within vault are returned as per the api
> 
> **Environment:** Vault 1.15.1 Backend dynamodb EKS - installed with helm chart 3 node cluster

---

This should be a fairly easy fix and affects OpenBao too: https://github.com/openbao/openbao/blob/main/builtin/logical/rabbitmq/path_roles.go#L110

**Comment by cipherboy** [comment]
@mr-miles Hmm, I can't reproduce this in the test suite using the InMem backend:

```go
func TestBackend_RoleReadCrash(t *testing.T) {
    // Reproducer from https://github.com/openbao/openbao/issues/97.
    config := logical.TestBackendConfig()
    config.StorageView = &logical.InmemStorage{}
    b, _ := Factory(context.Background(), config)
    storage := config.StorageView
    
    cleanup, uri := prepareRabbitMQTestContainer(t)
    defer cleanup()
    
    req := &logical.Request{
        Operation: logical.UpdateOperation,
        Path:      "config/connection",
        Storage:   storage,
        Data: map[string]interface{}{
            "connection_uri": uri,
            "username":       "guest",
            "password":       "guest",
        },  
    }       
    
    resp, err := b.HandleRequest(context.Background(), req)
    if err != nil || (resp != nil && resp.IsError()) {
        t.Fatalf("bad: err: %v resp: %#v", err, resp)
    }
    
    req = &logical.Request{
        Operation: logical.UpdateOperation,
        Path:      "roles/newrole",
        Storage:   storage,
        Data: map[string]interface{}{
            "vhosts": `{"/":{"write": "._", "read": "._"}}`,
        },
    }       
 
    resp, err = b.HandleRequest(context.Background(), req)
    if err != nil || (resp != nil && resp.IsError()) {
        t.Fatalf("bad: err: %v resp: %#v", err, resp)
    }
    
    req.Operation = logical.ReadOperation
    req.Data = nil
    
    resp, err = b.HandleRequest(context.Background(), req)
    if err != nil || (resp != nil && resp.IsError()) {
        t.Fatalf("bad: err: %v resp: %#v", err, resp)
    }
}
```

Two things that'd be helpful:

 1. Can you capture the panic you're seeing from the Vault logs?
 2. If you [enable `sys/raw`](https://github.com/openbao/openbao/blob/main/website/content/docs/configuration/index.mdx#L167-L169), could you then do a [read operation](https://github.com/openbao/openbao/blob/main/website/content/api-docs/system/raw.mdx) on the written config? 

Your hunch about storage backend might be right -- OpenBao has opted only for the raft storage backend. But, the other hunch is around structs/mapstructure, as we've generally preferred JSON over these now.

**Comment by cipherboy** [comment]
I cannot reproduce as of 9d05e85854da17ea2155b12247bcacd3034131f9 using the Raft storage backend either; I'd suggest moving to that as DynamoDB is a community supported backend (upstream; it has been removed from OpenBao).

**Comment by cipherboy** [comment]
@mr-miles @hghaf099 I understand now. :-)

Your reproducer doesn't work because the issue is _not_ with `vhosts` but with `vhost_topics`, that you didn't include on your original request. My reproducer didn't work because the crash _isn't_ in the plugin, but in the audit system, which your new stacktrace shows. :-)

<details>

<summary> Consider this reproducer which sets a permissive `vhost_topics`: </summary>

```go
func TestBackend_RoleReadCrash(t *testing.T) {
    // Reproducer from https://github.com/openbao/openbao/issues/97.

    coreConfig := &vault.CoreConfig{
        LogicalBackends: map[string]logical.Factory{
            "rabbitmq": Factory,
        },
        EnableRaw: true,
    }
    cluster := vault.NewTestCluster(t, coreConfig, &vault.TestClusterOptions{
        HandlerFunc: vaulthttp.Handler,
    })
    cluster.Start()
    defer cluster.Cleanup()
    client := cluster.Cores[0].Client

    cleanup, uri := prepareRabbitMQTestContainer(t)
    defer cleanup()

    err := client.Sys().Mount("rabbitmq", &api.MountInput{
        Type: "rabbitmq",
    })
    if err != nil {
        t.Fatalf("failed to mount: %v", err)
    }

    resp, err := client.Logical().Write("rabbitmq/config/connection", map[string]interface{}{
        "connection_uri": uri,
        "username":       "guest",
        "password":       "guest",
    })
    if err != nil {
        t.Fatalf("bad: err: %v resp: %#v", err, resp)
    }

    resp, err = client.Logical().Write("rabbitmq/roles/newrole", map[string]interface{}{
        "tags": "administrator",
        "vhosts": `
{
  "/": {
    "configure": ".*",
    "write": ".*",
    "read": ".*"
  }
}
`,
        "vhost_topics": `
{
    "/": {
        "amq.topic": {
            "write": ".*",
            "read": ".*"
        }
    }
}
`,
    })
    if err != nil {
        t.Fatalf("bad: err: %v resp: %#v", err, resp)
    }

    resp, err = client.Logical().Read("rabbitmq/roles/newrole")
    if err != nil {
        t.Fatalf("bad: err: %v resp: %#v", err, resp)
    }
    t.Logf("response: %#v", resp)

    mount := findStorageMountUuid(t, client, "rabbitmq")
    resp, err = client.Logical().Read("sys/raw/logical/" + mount + "/role/newrole")
    if err != nil {
        t.Fatalf("bad: err: %v resp: %#v", err, resp)
    }
    t.Logf("raw response: %#v", resp)
}

func findStorageMountUuid(t *testing.T, client *api.Client, mount string) string {
    resp, err := client.Logical().Read("sys/mounts/" + mount)
    require.NoError(t, err)
    require.NotNil(t, resp)
    require.NotNil(t, resp.Data)
    require.NotEmpty(t, resp.Data["uuid"])
    pkiMount := resp.Data["uuid"].(string)
    require.NotEmpty(t, pkiMount)
    return pkiMount
}
```

</details>


This outputs the crash [from your later comment](https://github.com/hashicorp/vault/issues/25112#issuecomment-1962340085):

<details>

<summary>Test execution output</summary>

```

response from structs: map[string]interface {}{"tags":"administrator", "vhost_topics":map[string]map[string]rabbitmq.vhostTopicPermission{"/":map[string]rabbitmq.vhostTopicPermission{"amq.topic":rabbitmq.vhostTopicPermission{Write:".*", Read:".*"}}}, "vhosts":map[string]interface {}{"/":map[string]interface {}{"configure":".*", "read":".*", "write":".*"}}}
2024-03-19T18:50:37.610-0400 [ERROR] TestBackend_RoleReadCrash.core0.audit: panic during logging: request_path=rabbitmq/roles/newrole error="reflect: reflect.Value.Set using unaddressable value"
  stacktrace=
  | goroutine 696 [running]:
  | runtime/debug.Stack()
  | \t/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
  | github.com/openbao/openbao/vault.(*AuditBroker).LogResponse.func1()
  | \t/home/cipherboy/GitHub/cipherboy/openbao/vault/audit_broker.go:165 +0x74
  | panic({0x2510c00?, 0xc0011c23f0?})
  | \t/usr/local/go/src/runtime/panic.go:770 +0x132
  | reflect.flag.mustBeAssignableSlow(0x10?)
  | \t/usr/local/go/src/reflect/value.go:272 +0x74
  | reflect.flag.mustBeAssignable(...)
  | \t/usr/local/go/src/reflect/value.go:259
  | reflect.Value.Set({0x2510c00?, 0xc000928960?, 0xc0011c2320?}, {0x2510c00?, 0xc0011c23e0?, 0x49babe0?})
  | \t/usr/local/go/src/reflect/value.go:2319 +0x65
  | github.com/openbao/openbao/audit.(*hashWalker).Primitive(0xc000912500, {0x2510c00?, 0xc000928960?, 0x80?})
  | \t/home/cipherboy/GitHub/cipherboy/openbao/audit/hashstructure.go:371 +0x3b4
  | github.com/mitchellh/reflectwalk.walkPrimitive(...)
  | \t/home/cipherboy/go/pkg/mod/github.com/mitchellh/reflectwalk@v1.0.2/reflectwalk.go:270
  | github.com/mitchellh/reflectwalk.walk({0x2510c00?, 0xc000928960?, 0x0?}, {0x29dad40, 0xc000912500})
  | \t/home/cipherboy/go/pkg/mod/github.com/mitchellh/reflectwalk@v1.0.2/reflectwalk.go:197 +0x63f
  | github.com/mitchellh/reflectwalk.walkStruct({0x2807160?, 0xc000928960?, 0x20?}, {0x29dad40, 0xc000912500})
  | \t/home/cipherboy/go/pkg/mod/github.com/mitchellh/reflectwalk@v1.0.2/reflectwalk.go:404 +0x448
  | github.com/mitchellh/reflectwalk.walk({0x2807160?, 0xc000928960?, 0x99?}, {0x29dad40, 0xc000912500})
  | \t/home/cipherboy/go/pkg/mod/github.com/mitchellh/reflectwalk@v1.0.2/reflectwalk.go:206 +0x445
  | github.com/mitchellh/reflectwalk.walkMap({0x2648f60?, 0xc0011bea20?, 0xc0011c2370?}, {0x29dad40, 0xc000912500})
  | \t/home/cipherboy/go/pkg/mod/github.com/mitchellh/reflectwalk@v1.0.2/reflectwalk.go:252 +0x2fa
  | github.com/mitchellh/reflectwalk.walk({0x2648f60?, 0xc0011bea20?, 0x15?}, {0x29dad40, 0xc000912500})
  | \t/home/cipherboy/go/pkg/mod/github.com/mitchellh/reflectwalk@v1.0.2/reflectwalk.go:200 +0x517
  | github.com/mitchellh/reflectwalk.walkMap({0x2648fc0?, 0xc0011be9f0?, 0x10?}, {0x29dad40, 0xc000912500})
  | \t/home/cipherboy/go/pkg/mod/github.com/mitchellh/reflectwalk@v1.0.2/reflectwalk.go:252 +0x2fa
  | github.com/mitchellh/reflectwalk.walk({0x25e3c80?, 0xc0011c2350?, 0x94?}, {0x29dad40, 0xc000912500})
  | \t/home/cipherboy/go/pkg/mod/github.com/mitchellh/reflectwalk@v1.0.2/reflectwalk.go:200 +0x517
  | github.com/mitchellh/reflectwalk.walkMap({0x2649320?, 0xc0011be8d0?, 0x45a61e?}, {0x29dad40, 0xc000912500})
  | \t/home/cipherboy/go/pkg/mod/github.com/mitchellh/reflectwalk@v1.0.2/reflectwalk.go:252 +0x2fa
  | github.com/mitchellh/reflectwalk.walk({0x2649320?, 0xc0011be8d0?, 0xc000912500?}, {0x29dad40, 0xc000912500})
  | \t/home/cipherboy/go/pkg/mod/github.com/mitchellh/reflectwalk@v1.0.2/reflectwalk.go:200 +0x517
  | github.com/mitchellh/reflectwalk.Walk({0x2649320?, 0xc0011be8d0?}, {0x29dad40, 0xc000912500})
  | \t/home/cipherboy/go/pkg/mod/github.com/mitchellh/reflectwalk@v1.0.2/reflectwalk.go:99 +0x117
  | github.com/openbao/openbao/audit.HashStructure(...)
  | \t/home/cipherboy/GitHub/cipherboy/openbao/audit/hashstructure.go:194
  | github.com/openbao/openbao/audit.hashMap(0xc00119dc20, 0xc0011be8d0, {0x0, 0x0, 0x0})
  | \t/home/cipherboy/GitHub/cipherboy/openbao/audit/hashstructure.go:100 +0x205
  | github.com/openbao/openbao/audit.HashResponse(0xc000739c00, 0xc000ccc6e0, 0x0, {0x0, 0x0, 0x0}, 0x0)
  | \t/home/cipherboy/GitHub/cipherboy/openbao/audit/hashstructure.go:148 +0x311
  | github.com/openbao/openbao/audit.(*AuditFormatter).FormatResponse(0xc000760130, {0x33d9068, 0xc0011be210}, {0x33b2b40, 0xc0011be8a0}, {0x0?, 0x0?, 0x0?, 0x0?}, 0xc000304b60)
  | \t/home/cipherboy/GitHub/cipherboy/openbao/audit/format.go:232 +0x2ef
  | github.com/openbao/openbao/helper/testhelpers/corehelpers.(*NoopAudit).LogResponse(0xc000760000, {0x33d9068, 0xc0011be210}, 0xc000304b60)
  | \t/home/cipherboy/GitHub/cipherboy/openbao/helper/testhelpers/corehelpers/corehelpers.go:300 +0x118
  | github.com/openbao/openbao/vault.(*AuditBroker).LogResponse(0xc000b3d410, {0x33d9068, 0xc0011be210}, 0xc000304b60, 0xc000b3d560)
  | \t/home/cipherboy/GitHub/cipherboy/openbao/vault/audit_broker.go:195 +0x398
  | github.com/openbao/openbao/vault.(*Core).handleCancelableRequest(0xc00095c308, {0x33d9068, 0xc0011be0f0}, 0xc000f93180)
  | \t/home/cipherboy/GitHub/cipherboy/openbao/vault/request_handling.go:790 +0x1945
  | github.com/openbao/openbao/vault.(*Core).switchedLockHandleRequest(0xc00095c308, {0x33d9068, 0xc00118fa70}, 0xc000f93180, 0x1)
  | \t/home/cipherboy/GitHub/cipherboy/openbao/vault/request_handling.go:525 +0x605
  | github.com/openbao/openbao/vault.(*Core).HandleRequest(...)
  | \t/home/cipherboy/GitHub/cipherboy/openbao/vault/request_handling.go:478
  | github.com/openbao/openbao/http.request(0xc00095c308, {0x33ca098, 0xc00118f980}, 0xc0011b4b40, 0xc000f93180)
  | \t/home/cipherboy/GitHub/cipherboy/openbao/http/handler.go:827 +0x7f
  | github.com/openbao/openbao/http.handler.handleLogical.handleLogicalInternal.func57({0x33ca098, 0xc00118f980}, 0xc0011b4b40)
  | \t/home/cipherboy/GitHub/cipherboy/openbao/http/logical.go:357 +0xa6
  | net/http.HandlerFunc.ServeHTTP(0xc00095c308?, {0x33ca098?, 0xc00118f980?}, 0xc00118ff20?)
  | \t/usr/local/go/src/net/http/server.go:2166 +0x29
  | github.com/openbao/openbao/http.handler.handleRequestForwarding.func35({0x33ca098, 0xc00118f980}, 0xc0011b4b40)
  | \t/home/cipherboy/GitHub/cipherboy/openbao/http/handler.go:761 +0x143
  | net/http.HandlerFunc.ServeHTTP(0xc000a66410?, {0x33ca098?, 0xc00118f980?}, 0x6d41a8?)
  | \t/usr/local/go/src/net/http/server.go:2166 +0x29
  | net/http.(*ServeMux).ServeHTTP(0xc000df15c0?, {0x33ca098, 0xc00118f980}, 0xc0011b4b40)
  | \t/usr/local/go/src/net/http/server.go:2683 +0x1ad
  | github.com/openbao/openbao/http.handler.wrapHelpHandler.func47({0x33ca098, 0xc00118f980}, 0xc0011b4b40)
  | \t/home/cipherboy/GitHub/cipherboy/openbao/http/help.go:28 +0xfd
  | net/http.HandlerFunc.ServeHTTP(0x0?, {0x33ca098?, 0xc00118f980?}, 0xc000a02b58?)
  | \t/usr/local/go/src/net/http/server.go:2166 +0x29
  | github.com/openbao/openbao/http.handler.wrapCORSHandler.func48({0x33ca098, 0xc00118f980}, 0xc0011b4b40)
  | \t/home/cipherboy/GitHub/cipherboy/openbao/http/cors.go:32 +0x389
  | net/http.HandlerFunc.ServeHTTP(0xc00095c308?, {0x33ca098?, 0xc00118f980?}, 0xc0011b82a0?)
  | \t/usr/local/go/src/net/http/server.go:2166 +0x29
  | github.com/openbao/openbao/http.handler.rateLimitQuotaWrapping.func49({0x33ca098, 0xc00118f980}, 0xc0011b4b40)
  | \t/home/cipherboy/GitHub/cipherboy/openbao/http/util.go:156 +0x9bf
  | net/http.HandlerFunc.ServeHTTP(0xc00118f8c0?, {0x33ca098?, 0xc00118f980?}, 0xc0012da560?)
  | \t/usr/local/go/src/net/http/server.go:2166 +0x29
  | github.com/openbao/openbao/http.wrapGenericHandler.func1({0x33caf68, 0xc000a0c770}, 0xc0011b47e0)
  | \t/home/cipherboy/GitHub/cipherboy/openbao/http/handler.go:428 +0xd35
  | net/http.HandlerFunc.ServeHTTP(0xc0011b46c0?, {0x33caf68?, 0xc000a0c770?}, 0xc00118f8f0?)
  | \t/usr/local/go/src/net/http/server.go:2166 +0x29
  | github.com/openbao/openbao/http.handler.wrapMaxRequestSizeHandler.func50({0x33caf68, 0xc000a0c770}, 0xc0011b46c0)
  | \t/home/cipherboy/GitHub/cipherboy/openbao/http/util.go:58 +0x122
  | net/http.HandlerFunc.ServeHTTP(0xc0010ea160?, {0x33caf68?, 0xc000a0c770?}, 0x0?)
  | \t/usr/local/go/src/net/http/server.go:2166 +0x29
  | github.com/openbao/openbao/http.handler.PrintablePathCheckHandler.func51({0x33caf68, 0xc000a0c770}, 0xc0011b46c0)
  | \t/home/cipherboy/go/pkg/mod/github.com/hashicorp/go-cleanhttp@v0.5.2/handlers.go:42 +0x8f
  | net/http.HandlerFunc.ServeHTTP(0x0?, {0x33caf68?, 0xc000a0c770?}, 0x0?)
  | \t/usr/local/go/src/net/http/server.go:2166 +0x29
  | net/http.serverHandler.ServeHTTP({0x0?}, {0x33caf68?, 0xc000a0c770?}, 0x0?)
  | \t/usr/local/go/src/net/http/server.go:3137 +0x8e
  | net/http.initALPNRequest.ServeHTTP({{0x33d9068?, 0xc000cdd980?}, 0xc000e5b508?, {0xc0005f21e0?}}, {0x33caf68, 0xc000a0c770}, 0xc0011b46c0)
  | \t/usr/local/go/src/net/http/server.go:3745 +0x231
  | net/http.(*http2serverConn).runHandler(0x44b23d?, 0xc000b43c20?, 0x33d9068?, 0xc00118e450?)
  | \t/usr/local/go/src/net/http/h2_bundle.go:6153 +0xbb
  | created by net/http.(*http2serverConn).scheduleHandler in goroutine 608
  | \t/usr/local/go/src/net/http/h2_bundle.go:6088 +0x21d
  
2024-03-19T18:50:37.610-0400 [ERROR] TestBackend_RoleReadCrash.core0.core: failed to audit response: request_path=rabbitmq/roles/newrole
  error=
  | 1 error occurred:
  | \t* panic generating audit log
  | 
  
    backend_test.go:418: bad: err: Error making API request.
        
        URL: GET https://127.0.0.1:41353/v1/rabbitmq/roles/newrole
        Code: 500. Errors:
        
        * internal error resp: (*api.Secret)(nil)
2024-03-19T18:50:44.235-0400 [INFO]  TestBackend_RoleReadCrash: cleaning up vault cluster
--- FAIL: TestBackend_RoleReadCrash (16.04s)
FAIL
FAIL	github.com/openbao/openbao/builtin/logical/rabbitmq	16.057s
FAIL
...
```

</details>

Augmented with a sloppy `fmt.Fprintf(os.Stderr, "\nresponse from structs: %#v\n", structs.New(role).Map())` in the plugin before the return.

Note the typing:

```
response from structs: map[string]interface {}{"tags":"administrator", "vhost_topics":map[string]map[string]rabbitmq.vhostTopicPermission{"/":map[string]rabbitmq.vhostTopicPermission{"amq.topic":rabbitmq.vhostTopicPermission{Write:".*", Read:".*"}}}, "vhosts":map[string]interface {}{"/":map[string]interface {}{"configure":".*", "read":".*", "write":".*"}}}
```

The audit subsystem doesn't support reflection into arbitrary response types, and I believe only supports Go primitives (based on past experience -- though, maybe this is untrue and supports reflection into exported types and not private types). This is why a lot of plugins do manual marshaling of response types. But here, `structs` is converting the `vhosts` into a native `map[string]interface{}`, but does not do the same with the `vhost_topics` (retaining the internal  `rabbitmq.vhostTopicPermission` type).

So, thank you! I'll open a PR with a patch doing custom serialization.
